# Generated by Django 3.2.20 on 2023-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursesyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
