# Generated by Django 3.2.20 on 2023-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0002_coursesyllabus_day_syllabus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coursesyllabus',
            new_name='course_syllabus',
        ),
    ]
