# Generated by Django 3.2.20 on 2023-07-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0003_rename_coursesyllabus_course_syllabus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_syllabus',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='course',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='course',
            new_name='syllabus',
        ),
    ]
