# Generated by Django 3.2.20 on 2023-07-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabustrackerapp', '0004_auto_20230708_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabustrackerapp.course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabustrackerapp.day')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabustrackerapp.syllabus')),
            ],
        ),
    ]
